/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Float
 #	author : miyako
 #	2019/02/27
 #
 # --------------------------------------------------------------------------------*/



// --- IEEE 754
void BLOB_to_float(sLONG_PTR *pResult, PackagePtr pParams);
void float_to_BLOB(sLONG_PTR *pResult, PackagePtr pParams);

typedef unsigned char float_size_t;
typedef uint32_t float_string_length_t;
typedef int float_precision_t;

typedef enum{
    
    float_convert_mode_e = 1,
    float_convert_mode_f = 0,
    float_convert_mode_g = 2
    
} float_convert_mode_t;

typedef enum{
    
    float_endian_little = 0,
    float_endian_big = 1
    
} float_endian_t;

#define float_precision_default (FLT_DECIMAL_DIG-1)

#define float_fmt_f "%.*f" /* Decimal floating point, lowercase */
#define float_fmt_e "%.*e" /* Scientific notation (mantissa/exponent), lowercase */
#define float_fmt_g "%.*g" /* Use the shortest representation: %e or %f */
